RDK:
    paths:
      # RDK标定数据存放路径
      calib_data_dir: "/root/calibration/0.0.2/calib_data/"
      # RDK标定日志存放路径
      # log_dir: "/root/calibration/0.0.2/log/"
      # RDK采集数据包存放路径
      rosbag_dir: 
        - "/root/calibration/0.0.2/pingshi_1/"
        - "/root/calibration/0.0.2/pingshi_2/"
        - "/root/calibration/0.0.2/pingshi_3/"
        # - "/root/calibration/0.0.2/fushi"

x86:
    paths:
      # x86标定数据存放路径
      calib_data_dir: "calib_data"
      # x86标定数据JSON存放路径
      calib_data_json_dir: "calib_data_json"
      # x86标定日志存放路径
      log_dir: "log"
      # x86采集数据包存放路径
      rosbag_dir: "rosbag"
    files:
      # 标定参数文件名
      calib_params_file: "calibration_result.json"


# 功能测试使用配置
RDK_test:
    paths:
      calib_data_dir: "/root/t/"
      log_dir: "/root/t/c/"
      rosbag_dir: 
        - "/root/t/b/"
        - "/root/t/a/"
x86_test:
    paths:
      calib_data_dir: "/home/hu/RDK/calib_tool/test_dir/A/"
      calib_data_json_dir: "/home/hu/RDK/calib_tool/test_dir/B/"
      log_dir: "/home/hu/RDK/calib_tool/test_dir/C/"
      rosbag_dir: "/home/hu/RDK/calib_tool/test_dir/D/"
    files:
      calib_params_file: "1.txt"
