RDK:
    paths:
      # RDK标定数据存放路径
      calib_data_dir: "/root/calibration/0.0.2/calib_data/"
      # RDK标定日志存放路径
      # log_dir: "/root/calibration/0.0.2/log/"
      # RDK采集数据包存放路径
      rosbag_dir: 
        - "/root/calibration/0.0.2/pingshi_1/"
        - "/root/calibration/0.0.2/fushi_1/"
        - "/root/calibration/0.0.2/yangshi_1/"
        # - "/root/calibration/0.0.2/fushi"

x86:
    paths:
      # x86标定数据存放路径
      calib_data_dir: "calib_data"
      # x86标定数据JSON存放路径
      calib_data_json_dir: "calib_data_json"
      # x86标定日志存放路径
      log_dir: "log"
      # x86采集数据包存放路径
      rosbag_dir: "rosbag"
    files:
      # 标定参数文件名
      calib_params_file: "calibration_result.json"

evo:
    # 轨迹文件路径 (TUM 格式)
    vio_results: 
      - "/mnt/c/Users/jianming.hu/Downloads/vio_package_1/v1/"
      - "/mnt/c/Users/jianming.hu/Downloads/vio_package_1/v2/"
      - "/mnt/c/Users/jianming.hu/Downloads/vio_package_1/v3/"
    tum_file: "trajectory/ov_est.tum"

    # 输出截图路径
    output_image: "vio_output_img/"

